apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: blogger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      namespace: blogger
    spec:
      containers:
        - name: auth-service
          image: hariharasudhan94/blogger-auth-service:latest
          ports:
            - protocol: TCP
              containerPort: 3001
          env:
            - name: JWT_SECRET
              value: secret
