apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: blogger
spec:
  selector:
    matchLabels:
      database: postgres
  template:
    metadata:
      labels:
        database: postgres
        namespace: blogger
    spec:
      containers:
        - name: postgres
          image: postgres:14.4-alpine3.16
          ports:
            - protocol: 'TCP'
              hostPort: 5432
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: blogger
