apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: blogger
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001