apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: blogger
spec:
  type: ClusterIP
  selector:
    database: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432